name: Grain
value: 1
---
name: Clothing
value: 4
---
name: Wool
value: 1
---
name: Cotton
value: 1
---
name: Tobacco
value: 2
---
name: Timber
value: 1
---
name: Coal
value: 1
---
name: Iron
value: 1
---
name: Gold
value: 5
---
name: Bread
value: 2
---
name: Steel
value: 3
---
name: Beer
value: 2