Human:
  - !NeedsInfo
    name: Tobacco
    consumeAmount: 2
  - !NeedsInfo
    name: Beer
    consumeAmount: 1

Orc:
  - !NeedsInfo
    name: Tobacco
    consumeAmount: 2
  - !NeedsInfo
    name: Beer
    consumeAmount: 1

Naga:
  - !NeedsInfo
    name: Tobacco
    consumeAmount: 2
  - !NeedsInfo
    name: Beer
    consumeAmount: 1

Dwarf:
  - !NeedsInfo
    name: Tobacco
    consumeAmount: 2
  - !NeedsInfo
    name: Beer
    consumeAmount: 2