Human:
  - !NeedsInfo
    name: Tobacco
    consumeAmount: 2.0
  - !NeedsInfo
    name: Beer
    consumeAmount: 1.0

Orc:
  - !NeedsInfo
    name: Tobacco
    consumeAmount: 2.0
  - !NeedsInfo
    name: Beer
    consumeAmount: 1.0

Naga:
  - !NeedsInfo
    name: Tobacco
    consumeAmount: 2.0
  - !NeedsInfo
    name: Beer
    consumeAmount: 1.0

Dwarf:
  - !NeedsInfo
    name: Tobacco
    consumeAmount: 2.0
  - !NeedsInfo
    name: Beer
    consumeAmount: 2.0