name: Grain Farm
isRawExtraction: true
good:
  !Good
  name: Grain
---
name: Sheep Homestead
isRawExtraction: true
good:
  !Good
  name: Wool
---
name: Cotton Farm
isRawExtraction: true
good:
  !Good
  name: Cotton
---
name: Tobacco Farm
isRawExtraction: true
good:
  !Good
  name: Tobacco
---
name: Forestry
isRawExtraction: true
good:
  !Good
  name: Timber
---
name: Coal Mine
isRawExtraction: true
good:
  !Good
  name: Coal
---
name: Iron Mine
isRawExtraction: true
good:
  !Good
  name: Iron
---
name: Gold Mine
isRawExtraction: true
good:
  !Good
  name: Gold
---
name: Bakery
isRawExtraction: false
inputNeeds:
    Grain: 10
good:
  !Good
  name: Bread
---
name: Steel Mill
isRawExtraction: false
inputNeeds:
  Iron: 5
  Coal: 4
good:
  !Good
  name: Steel
---
name: Brewery
isRawExtraction: false
inputNeeds:
  Grain: 20
good:
  !Good
  name: Beer
---
name: Tailor
isRawExtraction: false
inputNeeds:
  Wool: 10
good:
  !Good
  name: Clothing